import mysql.connector
import bcrypt

# mysql connection
conn = mysql.connector.connect(host="localhost", user="root", password="root")
cursor = conn.cursor()

# create db
cursor.execute("CREATE DATABASE IF NOT EXISTS recipesapp")
cursor.execute("USE recipesapp")

cursor.execute("""
DROP TABLE IF EXISTS ingredients;
""")
cursor.execute("""
DROP TABLE IF EXISTS recipes;
""")
cursor.execute("""
DROP TABLE IF EXISTS users;
""")

cursor.execute("""DROP TABLE IF EXISTS users;""")

# recipes table
cursor.execute("""
CREATE TABLE recipes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    description TEXT,
    imageUrl VARCHAR(255),
    created_by VARCHAR(255) DEFAULT 'admin'
)
""")

# ingredients table
cursor.execute("""
CREATE TABLE ingredients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    recipe_id INT,
    name VARCHAR(255),
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
)
""")
conn.commit()

# users table
cursor.execute("""
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('user','admin') DEFAULT 'user'
)
""")

# @development
# admin user
username = "admin"
password = "1234"
role = "admin"
hashed_pw = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
cursor.execute(
    "INSERT INTO users (username, password, role) VALUES (%s, %s, %s)",
    (username, hashed_pw.decode("utf-8"), role),
)

# seeds
recipes = [
    {
        "title": "Tortilla de patatas",
        "description": "Receta tradicional española",
        "ingredients": ["Huevos", "Patatas", "Aceite", "Sal"],
        "imageUrl": "https://recetasdecocina.elmundo.es/wp-content/uploads/2025/02/tortilla-de-patatas-1.jpg",
    },
    {
        "title": "Paella",
        "description": "Arroz valenciano con mariscos",
        "ingredients": ["Arroz", "Langostinos", "Azafrán", "Pimiento"],
        "imageUrl": "https://imag.bonviveur.com/paella-de-pollo.jpg",
    },
    {
        "title": "Pizza margarita",
        "description": "Receta tradicional italiana",
        "ingredients": ["Harina", "Levadura", "Tomate", "Mozarella", "Albahaca"],
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
    },
    {
        "title": "Tortitas",
        "description": "Desayuno perfecto",
        "ingredients": ["Harina", "Mantequilla", "Azúcar", "Huevos", "Leche", "Levadura"],
        "imageUrl": "https://recetasdecocina.elmundo.es/wp-content/uploads/2024/10/receta-de-tortitas-1024x683.jpg",
    }
]

# Insertar recetas e ingredientes
for recipe in recipes:
    cursor.execute(
        "INSERT INTO recipes (title, description, imageUrl) VALUES (%s, %s, %s) ON DUPLICATE KEY UPDATE description=%s",
        (
            recipe["title"],
            recipe["description"],
            recipe["imageUrl"],
            recipe["description"],
        ),
    )
    recipe_id = cursor.lastrowid  # ID generated by AUTO INCREMENT

    if recipe_id == 0:
        cursor.execute("SELECT id FROM recipes WHERE title = %s", (recipe["title"],))
        recipe_id = cursor.fetchone()[0]

    for ingredient in recipe["ingredients"]:
        cursor.execute(
            "INSERT INTO ingredients (recipe_id, name) VALUES (%s, %s)",
            (recipe_id, ingredient),
        )

conn.commit()
conn.close()

print("Recetas guardadas en MySQL correctamente.")
